---
  # Todo:
  #   Break this file into separate files.
  #   Replace reboot with SSH session logoff after default user group change.
- hosts: all
  become: true
  become_method: sudo

  # The internel "setup" module is called against hosts automatically. Disable.
  # Caused error since python interpreter not part of Arch base.
  # https://docs.ansible.com/ansible/setup_module.html
  gather_facts: false

  # Variables
  vars:
    default_user: vagrant

  tasks:
    # Sync package databases wuthout upgrading system. This ensures that the
    # task to install Python requests the correct versions from the mirrors.
  - name: Sync package databases
    raw: pacman -Syy --noprogressbar

    # Arch base group does not include Python, which Ansible needs.
  - name: Install Python 2 and Python 3 interpreters
    raw: pacman -S python2 python --noconfirm --noprogressbar

    # It is necessary to sync databases and upgrade first in order to ensure
    # that outdated versions of the specific packages in the following tasks are
    # not requested from mirrors.
  - name: Perform full system upgrade
    pacman:
      update_cache: true
      upgrade: true
    register: pacman_system_upgrade

  # On Arch, Docker depends upon bridge-utils core package which is not included
  # in base group. At minimum, a reboot is required to start Docker. Perhaps
  # a manual loading of kernel module is possible without reboot?
  - name: Install Docker engine
    pacman:
      name: docker
      state: present
    register: pacman_docker_install

  # Given that the default Vagrant user already has root access without
  # additional authentication, the seurity implications are less severe. Just
  # watch the combination of Vagrant shared host directories and Docker
  # container network access from within the VM.
  # https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
  - name: Create docker Unix group
    group:
      name: docker
      state: present

  # Register variable to trigger reboot. A SSH session logoff would be better.
  - name: Add default user to docker Unix group
    user:
      append: true
      groups: docker
      name: "{{ default_user }}"
    register: user_groups_modified

  # If pacman operation or default user modification succeeded, reboot host and
  # wait for it to return
  - block:

    # Note that this task was changed from using the "command" module to "raw".
    # As of version 2.0.2.0, Ansible's command module implementation is:
    # 1) Connect SSH, 2)SFTP a temp file from host to target, 3) SSH back in
    # to execute temp file through Python and subsequently delete the file.
    # Obviously, step 3 was unable to be executed when the target machine
    # reboots and thus Ansible threw an "unreachable" status error that could
    # not be caught by ignore_errors.
    # https://github.com/ansible/ansible/issues/10472
    # https://docs.ansible.com/ansible/playbooks_async.html
    - name: Reboot host block
      async: 0
      raw: systemctl reboot
      ignore_errors: true
      poll: 0

    # Using ansible_ssh_* variables because the inventory file generated by
    # Vagrant specifies them.
    # The Ansible documentation is infuriatingly scattered and descriptions sparse.
    # Without search_regex, the task reports unchanged and returns after delay.
    # https://docs.ansible.com/ansible/wait_for_module.html#examples
    # http://stackoverflow.com/a/32383333
    - name: Wait for host reboot block
      become: false
      connection: local
      ignore_errors: true
      wait_for:
        connect_timeout: 10
        delay: 20
        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        port: "{{ ansible_ssh_port }}"
        search_regex: OpenSSH
        state: started
        timeout: 300

    when:
      pacman_system_upgrade.changed
      or pacman_docker_install.changed
      or user_groups_modified.changed

  # As of 216-03-11, necessary for virtualbox-guest-dkms package in order to
  # build kernel modules for VirtualBox guest additions.
  - name: Install Linux headers
    pacman:
      name: linux-headers
      state: present

  # Note that this package depends on python-setuptools and will install it.
  - name: Install python-pip
    pacman:
      name: python-pip
      state: present

  # Modify alias in default user's .bashrc to personal preference.
  - name: Enable "la" bash alias in .bashrc
    lineinfile:
      dest: /home/{{ default_user }}/.bashrc
      line: alias la='ls -Alh --color'
      regexp: '^alias la='
      state: present
    notify:
      - Source .bashrc

  - name: Enable Docker engine daemon
    command: systemctl enable docker

  - name: Start Docker engine daemon
    command: systemctl start docker

  handlers:
  - name: Source .bashrc
    shell: source /home/{{ default_user }}/.bashrc
