---
- hosts: all
  become: true
  become_method: 'sudo'

  # The internel "setup" module is called against hosts automatically. Disable.
  # https://docs.ansible.com/ansible/setup_module.html
  gather_facts: false

  tasks:

    # Arch base group does not include Python, which Ansible needs.
  - name: Install Python 2 and Python 3 interpreters
    raw: pacman -S python2 python --noconfirm --noprogressbar

  - name: Perform full system upgrade
    pacman:
      update_cache: true
      upgrade: true

  - name: Install Ruby interpreter
    pacman:
      name: ruby
      state: present
